/**
 * Shared types used across the whole mesh.
 *
 * Keeping them in one file means a reader can understand the "vocabulary" of
 * the system (decisions, risk factors, stage traces) before reading any logic.
 */

/**
 * The four possible verdicts for a request.
 *  - ALLOW         : forwarded to the destination service.
 *  - MONITOR       : forwarded, but flagged in the audit log / dashboard because
 *                    the risk score is elevated (medium risk).
 *  - STEP_UP_AUTH  : NOT forwarded. The caller must retry with a valid one-time
 *                    TOTP code in the `X-Service-TOTP` header (high risk).
 *  - BLOCK         : NOT forwarded. Hard failure or critical risk.
 */
export type Decision = 'ALLOW' | 'MONITOR' | 'STEP_UP_AUTH' | 'BLOCK';

/** Human-friendly bucket for a 0-100 risk score. */
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * One contribution to a risk score. The score is *always* the sum of these, so
 * an analyst can see exactly why a request scored what it did (explainability).
 */
export interface RiskFactor {
  /** Stable machine-readable name, e.g. NEW_SERVICE_PAIR. */
  code: string;
  /** Points added to the 0-100 score. */
  points: number;
  /** Human-readable explanation shown in the dashboard. */
  detail: string;
}

/**
 * A breadcrumb left by each pipeline stage. Returned to the caller (and stored in
 * the audit log) so you can replay *how* a decision was reached.
 */
export interface StageTrace {
  stage: string;
  outcome: 'pass' | 'fail' | 'flag';
  detail: string;
}

/** Everything the pipeline needs to know about one incoming request. */
export interface PipelineInput {
  /** Unique id for this single request (generated by the proxy). */
  requestId: string;
  /**
   * Correlates several hops that belong to one logical call chain. Services
   * should forward the same X-Trace-Id when they call each other. Lateral
   * movement detection is built on this.
   */
  traceId: string;
  /** Remote IP address of the caller. */
  ip: string;
  method: string;
  /** Path to forward to the destination, e.g. /orders/list (without /api/proxy). */
  path: string;
  /** Value of the X-Destination-Service header. */
  destination?: string;
  /**
   * Value of the (untrusted!) X-Service-ID header. We never use it to decide who
   * the caller is — the signed token does that — we only cross-check it to catch
   * spoofing attempts.
   */
  claimedService?: string;
  /** Raw Authorization header ("Bearer <jwt>"). */
  authorization?: string;
  /** Value of the X-Service-TOTP header, used for step-up authentication. */
  totp?: string;
  /** Parsed JSON body (if any). */
  body: unknown;
  /** Size of the request body in bytes (from Content-Length). */
  payloadBytes: number;
}

/** The pipeline's final answer for one request. */
export interface PipelineResult {
  requestId: string;
  traceId: string;
  decision: Decision;
  /** HTTP status the proxy should answer with when NOT forwarding. */
  httpStatus: number;
  /** Machine-readable reason, e.g. TOKEN_REPLAY, NO_POLICY, RISK_CRITICAL. */
  reason: string;
  /** 0-100. For hard failures this is a fixed severity (see config). */
  riskScore: number;
  riskLevel: RiskLevel;
  /** Authenticated service id (only set once authentication succeeded). */
  source?: string;
  destination?: string;
  method: string;
  path: string;
  factors: RiskFactor[];
  stages: StageTrace[];
  /** True when a risky request was let through because a valid TOTP was supplied. */
  mfaSatisfied: boolean;
  /**
   * Set when a policy DENIED the request but dry-run mode let it through.
   * "This request would have been blocked if the policy were enforced."
   */
  dryRunViolation?: { reason: string; policyId?: string };
  /** Time spent inside the security pipeline only (not the downstream call). */
  durationMs: number;
  timestamp: number;
}
